"""
CreateMap: combines a Tilemap (buildings) with a Roads layer (MST + optional extras).
"""
import random
from .tilemap import Tilemap
from .roads import Roads
from ..display import Display

class CreateMap:
    """Owns the tilemap and the road network, renders both onto the display."""
    def __init__(self, display_obj: Display,
                 num_houses: int, num_offices: int,
                 building_width: int, building_height: int,
                 rng: random.Random | None = None) -> None:
        """
        Args:
            display_obj: Display surface (real or headless).
            num_houses: Number of houses to place.
            num_offices: Number of offices to place.
            building_width: Building tile width in pixels.
            building_height: Building tile height in pixels.
            rng: Optional injected RNG for deterministic building placement.
        """
        self.__building_width: int = building_width
        self.__building_height: int = building_height
        self.__display: Display = display_obj
        print("Generating Tilemap...")
        self.__tilemap: Tilemap = Tilemap(self.__display,
                                          num_houses, num_offices,
                                          building_width, building_height,
                                          rng=rng)
        self.__roads: Roads | None = None  # Built lazily in draw() once we know placement

    def draw(self, pause: bool, additional_roads: bool) -> None:
        """
        Handles the map drawing.
        Draws the buildings on the tilemap (renders it).
        Draws the roads onto the tilemap.

        Args:
            pause (bool): True if display process to be shown, False if not.
            additional_roads (bool): True if additional roads to be drawn, False if not.
        """
        print("Drawing Tilemap...")
        self.__tilemap.render(pause) # Draw tilemap
        print("Calculating Roads...")
        self.__roads = Roads(self.__display, # Calculate roads
                                   self.__tilemap.get_map(),
                                   self.__building_width, self.__building_height,
                                   additional_roads)
        print("Drawing Roads...")
        self.__roads.draw_roads(pause) # Draw roads
        self.__display.update()

    def get_tilemap(self) -> Tilemap:
        """
        Returns the Tilemap object.
        
        Returns:
            tilemap.Tilemap: Tilemap object that manages the buildings on the map.
        """
        return self.__tilemap

    def get_roads(self) -> dict[tuple[int, int], list[tuple[tuple[int, int], int]]]:
        """
        Returns the roads generated by the Roads class.

        Returns:
            dict[tuple[int, int], list[tuple[tuple[int, int], int]]]: Dictionary of roads generated.
        """
        return self.__roads.get_roads()
